name: Sync directory with S3 bucket
description: Composite action to configure AWS and deploy app bundle to S3

inputs:
  bucket-name:
    description: 'S3 bucket name'
    required: true
  bundle-dir:
    description: 'Bundle directory'
    required: false
    default: 'dist'

runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-region: 'eu-north-1'

    - name: Sync S3 bucket
      run: aws s3 sync ${{ inputs.bundle-dir }} s3://${{ inputs.bucket-name }}
      shell: bash

    - name: Invalidate CloudFront Cache
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
      shell: bash